# Generated by Django 2.1.5 on 2019-07-27 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='others_items', to='wishlist.User'),
        ),
    ]
