# Generated by Django 2.1.5 on 2019-07-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20190726_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='others',
        ),
        migrations.AddField(
            model_name='item',
            name='others',
            field=models.ManyToManyField(blank=True, null=True, related_name='others_items', to='wishlist.User'),
        ),
    ]
