# Generated by Django 2.1.5 on 2019-02-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190218_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desc', to='courses.Course'),
        ),
    ]
