# Generated by Django 2.1.5 on 2019-02-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190218_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='description', to='courses.Course'),
        ),
    ]
