# Generated by Django 2.1.5 on 2019-02-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190218_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='description',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='courses.Course'),
        ),
    ]
