# Generated by Django 2.1.5 on 2019-11-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
