# Generated by Django 2.1.5 on 2019-08-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(related_name='wished_bys', to='wishlist.User'),
        ),
    ]
