# Generated by Django 2.1.5 on 2019-02-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0006_auto_20190217_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='book_authors.Author'),
        ),
    ]
